services:
  # MongoDB Service
  mongodb:
    image: mongo:7.0
    container_name: taskflow-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: taskflow
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - taskflow-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Next.js Application
  taskflow:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: taskflow-nextjs
    restart: unless-stopped
    ports:
      - "9002:9002"
    environment:
      # Database Configuration
      DB_TYPE: mongodb
      MONGODB_URI: mongodb://admin:password@mongodb:27017/taskflow?authSource=admin
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: taskflow
      MONGODB_TASKS_COLLECTION: tasks
      MONGODB_TEMPLATES_COLLECTION: templates
      MONGODB_DAILY_PLANS_COLLECTION: dailyPlans
      # Next.js Development Configuration
      NODE_ENV: development
      HOSTNAME: 0.0.0.0
      PORT: 9002
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - taskflow-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  taskflow-network:
    driver: bridge
